version: '3'

services: 

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        container_name: elasticsearch
        hostname: elasticsearch
        environment: 
            - "discovery.type=single-node"
        ports: 
            - '9200:9200'
            - '9300:9300'
        
    kibana:
        image: mtkell/kibana
        container_name: kibana
        hostname: kibana
        ports: 
            - '5601:5601'
        depends_on: elasticsearch

    logstash:
        image: mtkell/logstash
        container_name: logstash
        hostname: logstash
        ports: 
            - '5044:5044'
            - '9600:9600'
            
        depends_on: elasticsearch

    
        